name: Docker

on:
  schedule:
    - cron: '28 17 * * *'
  push:
    branches: [ "main" ]

env:
  CONTEXT_PATH: ./squid
  REGISTRY: docker.io
  IMAGE_NAME: tetsuyainfra/caching-by-squid

jobs:
  # ==========================
  # Build Job
  # ==========================
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # 5.8.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # mainブランチにpushがあればlatestタグを付与
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch
            type=ref,event=pr

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build Docker image
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ env.CONTEXT_PATH }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # 単一プラットフォームでビルドしているのでloadオプションを使える
          # (Actionsのrunner上のDockerデーモンにイメージをロードする=docker runで使えるようにする)
          # (マルチプラットフォームにするときは, outputオプションをつかう)
          load: true
          # ローカルキャッシュにする
          cache-to: type=local,dest=./tmp/.buildx-cache

      - name: Get package.list in container
        run: |
          docker run --rm --entrypoint bash \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            -c 'cat /usr/share/rocks/packages.list' | tee new_package.list

      # Cache package.list
      # new_package.listのハッシュ値をキーにしてキャッシュを探す
      - name: Cache package.list
        id: package-list-cache
        uses: actions/cache@v4
        with:
          path: package.list
          key: commit-${{ github.sha }}_package-list-${{ hashFiles('new_package.list') }}


      # キャッシュヒットした→ バージョンが同じ
      # キャッシュヒットしなかった → バージョンが異なる（おそらく新しい
      # キャッシュヒットしなかったら
      # actions/cacheにキャッシュしてもらえるようnew_package.listをpackage.listにコピーする
      - name: Cache hit then will not publish
        if: steps.package-list-cache.outputs.cache-hit != 'true'
        id: is_published
        run: |
          cp new_package.list package.list
          echo result=false >> $GITHUB_OUTPUT

      - name: Push Docker image
        id: push
        if: steps.is_published.outputs.result == 'false'
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ${{ env.CONTEXT_PATH }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=./tmp/.buildx-cache
